apiVersion: v1
kind: Service
metadata:
  name: ai-service-backend
  namespace: ai-service
spec:
  selector:
    app: ai-service-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
