apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-service-config
  namespace: ai-service
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_NAME: ai_service
  DB_URL: jdbc:mysql://mysql:3306/ai_service?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  AI_BASE_URL: http://ai-mock-service:8000
  AI_ANALYSIS_PATH: /api/v1/analyze
